apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: alpine
    image: alpine:3.6
#    command: ['/bin/sh', '-c', 'apk --update --no-cache --virtual build-dependencies add apache2-utils 
#    && htpasswd -b -c /etc/.htpasswd user1 password1 && sleep 3000']
#    command: ['/bin/sh', '-c', 'apk add apache2-utils && htpasswd -b -c /etc/.htpasswd user1 password1']
